artifact_location: file:///home/berto/Demand-forecasting-in-retail/mlflow_results/425292371833343006
creation_time: 1763988788982
experiment_id: '425292371833343006'
last_update_time: 1763988788982
lifecycle_stage: active
name: full_pipeline_model_comparison
